// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYn5UGS1OqclU7HoqgmteH94ctprjuMr8',
    appId: '1:463578733203:web:9afe58b014c51144d60b66',
    messagingSenderId: '463578733203',
    projectId: 'testecampo2-813a9',
    authDomain: 'testecampo2-813a9.firebaseapp.com',
    storageBucket: 'testecampo2-813a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUYHg_F1E1fdtlCr_SsY1HMVUYMpa6oEA',
    appId: '1:463578733203:android:9c3253cbec50f60fd60b66',
    messagingSenderId: '463578733203',
    projectId: 'testecampo2-813a9',
    storageBucket: 'testecampo2-813a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvellckVdteSICO1vyg07ctl7Ql2a1AHg',
    appId: '1:463578733203:ios:3db8678282849c47d60b66',
    messagingSenderId: '463578733203',
    projectId: 'testecampo2-813a9',
    storageBucket: 'testecampo2-813a9.appspot.com',
    iosBundleId: 'com.example.projetoIdr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvellckVdteSICO1vyg07ctl7Ql2a1AHg',
    appId: '1:463578733203:ios:3db8678282849c47d60b66',
    messagingSenderId: '463578733203',
    projectId: 'testecampo2-813a9',
    storageBucket: 'testecampo2-813a9.appspot.com',
    iosBundleId: 'com.example.projetoIdr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYn5UGS1OqclU7HoqgmteH94ctprjuMr8',
    appId: '1:463578733203:web:6dd6bf40e59f0fe3d60b66',
    messagingSenderId: '463578733203',
    projectId: 'testecampo2-813a9',
    authDomain: 'testecampo2-813a9.firebaseapp.com',
    storageBucket: 'testecampo2-813a9.appspot.com',
  );

}